spring:
  datasource:
    url: jdbc:mysql://${mysql.ip}:3306/dkm_pay?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
mysql:
  ip: 192.168.10.254
