server:
  port: 8003
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://${mysql.ip}:3306/dkm_pay?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: advertise-resource
  jmx:
    enabled: false

app:
  workerId: 9
  dataCenterId: 1

mysql:
  ip: 192.168.10.133
