server:
  port: 8000
spring:
  application:
    name: admin-zuul
  jmx:
    enabled: false
zuul:
  routes:
    user-url:
      path: /user/**
      url: http://${service.ip}:20002/user/
    pay-url:
      path: /pay/**
      url: http://${service.ip}:20001/pay/
service:
  ip: 192.168.10.254

app:
  workerId: 9
  dataCenterId: 1
