server:
  port: 8000
spring:
  application:
    name: admin-zuul
  jmx:
    enabled: false
zuul:
  routes:
    user-url:
      path: /user/**
      url: http://${service.ip}:8002/

service:
  ip: localhost

app:
  workerId: 9
  dataCenterId: 1
