spring:
  datasource:
    url: jdbc:mysql://${mysql.ip}:3306/dkm_pay?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
pay:
  # 生产环境
  devUrl: https://openapi.alipay.com/gateway.do
  #沙箱环境 appId: 2016092500591778
  testUrl: https://openapi.alipaydev.com/gateway.do
  aliPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTCw0ekMpD3o6n2zR2Kg/rH8/1saE14vIcX2ms7lzOiZgGYw+cP6/scuoGnkLK9WvSOwVv8t8MnsTWhXy1M0m+AEM/DexY0yOP49+Jn+vcdqFlZ2JGxpsw2qBHsMx2eVpbGsCkTNtR6kHDpIyu/kZbWS9DyXdzR5Ux4ks0aaTsAlyE/lHa0XQr6VtzE5dg6aBp33FSEcu1sVtXCyUE9zC3KXWHiRfN15d3peRzidCtxqgynqd3ssWAUIK+0GInzXprAJwGasXUNL+6piF38uLHq4J+WdwMVvqP5VYmwDr497QJTw4t/2AFDAH8nHAIjgVZI6JuPwIFVReWQ0vFIvwLAgMBAAECggEATwSCQwF/We4Ih7zBZcTV9PkSSjHZ5G02rXzj+kW9Je/KpgmNHLmTyvozuYqkA43kcvB6VrIe5YDEvnV4fffYEnXSt9ckuRVE6Wkulz7zdrZMM8WDvHA8Rwx0mqMNywYg2J+ppVrJe2A0g2Ym7pZyDV3VHpJeUSFqMSVDdzpe76Y77wfwy1+q9+TRFGvS4GazNsnAR+1IXawpf+ZFzWHri9K0ejQm6agDmoW+vjAoWDLsBy0Iluc3UqojVRbCo88niUOuKTz5NMw+z15u9d082dewTvbuDXFEnUktpvXU9lltFazAtt9/6A6bJFAC1wPzl+qJPc5SO9xBnENu9eB1EQKBgQD+SSJQJNPTgVEO+ga6xix8a278rrva4c9aY9hG5ptFA3c4S4Z2FWC4Z6hGhwCxsPCYv2IPTPfLifHcBK6ynFdBcuP+D99M2vVDGIQt2XfASggAACyYPt9RWT8+hIuAqWFsB/DpOc+I7pKvlQsm360NRmEADIqm2J804oC50tGCRwKBgQDUd0kyuzkh+Z177d4GmsOc6lXsnlp3K9i/fnVD3OK+l9viQD1LTBmBaX1ye4SmdthPvGwQ6rIl3WY0ZETI0/N29N1r0D6es3VS/VgS1LVnpiIZiDia6Z9IvvyctoN5sDDRWiG2qYcM3PEupvdOeD5GDKUzpPV6LdUFxZbYCpH2HQKBgQDN1u/Cxnz+WlD+eaCW8rKyKNlYDC4fGema9vXtNuF7tTl9xY1b6yQ3Qhmytbf3Hw8z5sB/OEPibJDvFI9CIFJ1tYYfdEPDV/9vx9m/r6lDa+ob7ggrWcG2fTM37V1r0jD9nVQDx3tbEhyFq3Wyix/vfggpXP2j3/jIe43OXnygIwKBgQCDX1rAZqm2C01IUtVlSg7IGNGWZHfVliQIjB3gH1WIugd5B3We+GgQ7/RkdGGaOIQaEYzUjPoolZRbsuAhOYUiOdgrkPEXWimibgomYqXkeAI/vU4a43fdGFLEZ8o11S7qVAvikUJzPq5WxWDHgWwoDiucGlS6/lnonrtdzHNiNQKBgEPGrDOt4KjdkMAZ6eCB2NYcoczt4uE7meDTsnpIxRzIbokcruW5DyCUOI+x+Yod5qJQsieLf1kKA4y7B+lzlsmdcSUFAdI9rFWutedu90CKW3Qo6wY3cLOHd4pnh2+JBmj87/zHI8UAwc0Pl7s6Ar/wyxIjqlYYowY5WygzfqRl
  aliPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr/YanWqRNNa4xl5cJE4N5iqwa8P9mU+LLYEmyd3vUYmaPN1w4x+qF/bFo0fR1J3BpAnVN8GpW524gK4w2y/K8hUuw4vEdFDnpAP2bYPIZVYZrJdQTdgqBIGeKYyMCke3ZJENamjHuIrSePd6V3k5lMFV2e9j6OUtH89Sam54SxKir6gxiUWL2V3W2EWJzV9+t+f2QJC8i0uIfFy2fslvPUMPEGLJWnmTMZ3I/tdjgOVb0OgEIF++6rRZEivK4mnnRyTXXONS1Lk0nu8WxpHBg3hdrRDbj1Pq0iDSM+GM5sBIzQJRgLAzArBbumibweat46C5jeV42vG5cC+bnHUUjQIDAQAB
  # 支付宝回调
  #  notifyServerUrl: http://www.fate-jie.top/returnPay/updateInfo
  notifyServerUrl: http://${serve.ip}:${serve.port}/pay/returnPay/updateInfo
wx:
  # 统一下单
  url: https://api.mch.weixin.qq.com/pay/unifiedorder
  # 微信异步回调
  #  notifyUrl: http://www.fate-jie.top/v1/wx/notify
  notifyUrl: http://${serve.ip}:${serve.port}/pay/v1/wx/notify
  # 退款接口
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  # 查询订单状态接口
  queryUrl: https://api.mch.weixin.qq.com/pay/orderquery
  # 查询订单退款接口
  queryRefundUrl: https://api.mch.weixin.qq.com/pay/refundquery
  # 微信发红包
  pay: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  certUrl: /root/cert/apiclient_cert.p12
  ip: 120.25.196.49
mysql:
  ip: 192.168.10.133
serve:
  ip: 192.168.10.133
  port: 20001
